### ISSUE TITLE
Does not use codeigniter

### ISSUE THREAD

**Issue by daviddesberg** [DaveRandom/Code39#1] opened 2013-01-24 19:19 UTC
Needs to use codeigniter.

**Comment by DaveRandom** [comment] 2013-01-25 22:02
Closing this issue because the lib was designed for NodeCakeIgniterQuery.js

**Closed as completed by DaveRandom** 2013-01-25 22:02 UTC
Labels: wontfix

**Comment by daviddesberg** [comment] 2013-01-25 22:59
I demand you add in MongoDbWebScale.js.rails support.
